Repository uncc-hice/edukona_backend, pull requests merged in 2024-11, with the labels that each got.

#62 Add Quiz Settings Management Command and Update Model
  api/management/__init__.py
  api/management/commands/__init__.py
  api/management/commands/copysettings.py
  api/migrations/0052_quiz_live_bar_chart_quiz_skip_count_per_student_and_more.py
  api/models.py
Labels: pr-description, 0.1.62

#64 Remove Timer Duration Setting from API
  api/consumers.py
  api/migrations/0053_remove_settings_timer_duration.py
  api/models.py
Labels: pr-description, 0.1.64

#63 Add WebSocket Tests Workflow
  .github/workflows/websocket-tests.yml
Labels: pr-description, 0.1.63, 0.1.63.1

#66 Update User Authentication to Use Email Instead of Username
  api/tests/tests.py
  api/views/user_views.py
Labels: pr-description, 0.1.66, 0.1.66.1

#61 add type to student response submission messages
  api/consumers.py
Labels: 0.1.61

#68 Add QuizByRecordingView to Fetch Quizzes by Recording ID
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.68, 0.1.68.1, 0.1.68.2

#70 Update Quiz and Recording Title Features
  api/serializers.py
  api/tests/tests.py
  api/views/quiz_views.py
  api/views/recordings_views.py
  api/views/session_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.70

#69 Add Lecture Summary Model and API Endpoint
  api/migrations/0054_lecturesummary.py
  api/models.py
  api/permissions.py
  api/serializers.py
  api/tests/tests.py
  api/views/session_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.69

#73 Update Django Test Workflow to Exclude Specific Test File and Adjust Coverage Threshold
  .github/workflows/django-test.yml
Labels: pr-description

#72 Enhanced User Deletion Process in DeleteUserView
  api/views/user_views.py
Labels: pr-description, 0.1.72, 0.1.72.1

#74 Set up Flake8 and update GitHub workflows for Python version and formatting tools
  .flake8
  .github/workflows/flake8-format.yml
  .github/workflows/python-black-check.yml
  pyproject.toml
Labels: pr-description, 0.1.74

#76 Revert line-length to 100
  .flake8
  .github/workflows/python-black-check.yml
  pyproject.toml
Labels: pr-description

#79 Migration Update for Incorrect Answer List Handling
  api/migrations/0054_auto_20241111_2121.py
  api/migrations/0055_merge_0054_auto_20241111_2121_0054_lecturesummary.py
  api/models.py
Labels: pr-description, 0.1.79

#81 Update Python Black Check Workflow to Use Latest Actions and Improved Logic
  .github/workflows/python-black-check.yml
Labels: pr-description

#77 Enhancements to User Authentication Tests and APIs
  api/tests/tests.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.77, 0.1.77.1

#82 ✨ Enhance Migration, Model, and View Definitions
  api/migrations/0054_auto_20241111_2121.py
  api/models.py
  api/views/question_views.py
  api/views/quiz_views.py
  api/views/recordings_views.py
  api/views/session_views.py
  api/views/user_views.py
Labels: pr-description, 0.1.82

#86 Add Duration Field and Update Recording Duration Functionality
  api/migrations/0057_instructorrecordings_duration.py
  api/models.py
  api/serializers.py
  api/tests/tests.py
  api/views/recordings_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.86

#78 Add Token Verification Feature
  api/tests/tests.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.78

#85 Enhance Permissions and Refactor Views for Quiz Sessions and Recordings
  api/permissions.py
  api/tests/tests.py
  api/views/quiz_views.py
  api/views/recordings_views.py
  api/views/session_views.py
  api/views/user_views.py
Labels: pr-description, 0.1.85

#80 Added GET endpoint for Lecture Summary
  api/migrations/0054_quiz_num_questions_quiz_question_duration.py
  api/migrations/0055_remove_quiz_num_questions_and_more.py
  api/migrations/0058_merge_20241113_0042.py
  api/temp_migrations/0056_merge_20241111_2228.py
  api/temp_migrations/0057_merge_20241111_2305.py
  api/temp_migrations/__init__.py
  api/tests/tests.py
  api/views/session_views.py
Labels: pr-description, 0.1.80

#90 Cloudwatch Logging Update w/ Sample Logging
  api/views/user_views.py
  hice_backend/settings.py
  requirements.txt
Labels: pr-description, 0.1.90, 0.1.90.1

#89 Add Incorrect Answer List to Question Multiple Choice Serializer
  api/serializers.py
  api/tests/test_question_views.py
  api/tests/tests.py
Labels: pr-description, 0.1.89

#92 Refactor Audio Upload and Recording Management URLs
  hice_backend/urls.py
Labels: pr-description, 0.1.92

#93 # Add Lecture Summary Retrieval Feature
  api/permissions.py
  api/tests/tests.py
  api/views/session_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.93

#95 Refactor URL endpoints for audio recordings in `urls.py`
  hice_backend/urls.py
Labels: pr-description, 0.1.95

#96 Enhance Lecture Summary Management with Update Functionality
  api/permissions.py
  api/tests/tests.py
  api/views/session_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.96

#97 Refactor QuestionMultipleChoice Model Methods
  api/models.py
Labels: pr-description, 0.1.97

#98 # Update Coverage Configuration, CI Workflow, and Model Methods
  .coveragerc
  .github/workflows/django-test.yml
Labels: pr-description, 0.1.98

#99 Enhance Quiz Retrieval with Sorting and Testing Improvements
  api/models.py
  api/tests/tests.py
Labels: pr-description, 0.1.99

#100 ✨ Add QuizSessionLog Model and Update Quiz Ordering
  api/migrations/0059_alter_quiz_options_quizsessionlog.py
  api/migrations/0060_alter_quizsessionlog_question_multiple_choice.py
  api/models.py
Labels: pr-description, 0.1.100
