Repository uncc-hice/edukona_backend, pull requests merged in 2024-09, with the labels that each got.

#7 Code Formatting Enhancements: Flake8 and Black Integration with No Logic Changes
  .github/workflows/flake8-format.yml
  .github/workflows/python-black-check.yml
  api/consumers.py
  api/models.py
  api/permissions.py
  api/serializers.py
  api/tests/tests.py
  api/views.py
  hice_backend/settings.py
Labels: 0.1.7

#8 Enhance PR Workflow to Include Automatic Description Generation
  .github/workflows/deploy-eb.yml
  .github/workflows/generate-pr-description.yml
  generate_description.py
Labels: pr-description, 0.1.8

#9 Add Transcript Field for Instructor Recordings and Update API Endpoint
  api/migrations/0037_instructorrecordings_transcript.py
  api/models.py
  api/serializers.py
  api/views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.9

#10 Enhance Instructor Recordings and Integrate AWS Lambda Functionality
  api/serializers.py
  api/views.py
  hice_backend/settings.py
Labels: pr-description, 0.1.10, 0.1.10.1

#12 KAN-8: Updated views, updated gitignore, updated requirements.txt
  .gitignore
  api/apps.py
  api/consumers.py
  api/migrations/0001_initial.py
  api/migrations/0002_remove_course_access_code.py
  api/migrations/0003_remove_course_university.py
  api/migrations/0004_question_quic_remove_student_courses_and_more.py
  api/migrations/0005_rename_quic_quiz.py
  api/migrations/0006_answer_quizinstance_userprofile_and_more.py
  api/migrations/0007_instructor_questionmultiplechoice_and_more.py
  api/migrations/0008_alter_questionmultiplechoice_table_and_more.py
  api/migrations/0009_alter_questionmultiplechoice_table_and_more.py
  api/migrations/0010_alter_questionmultiplechoice_table.py
  api/migrations/0011_alter_userresponse_table.py
  api/migrations/0012_alter_student_user.py
  api/migrations/0013_alter_instructor_user.py
  api/migrations/0014_quizsession_quizsessionstudent_and_more.py
  api/migrations/0015_remove_quizsession_quiz_alter_userresponse_question_and_more.py
  api/migrations/0016_alter_userresponse_quiz_session.py
  api/migrations/0017_alter_quizsessionstudent_quiz_session.py
  api/migrations/0018_alter_userresponse_student.py
  api/migrations/0018_quizsession_served_questions.py
  api/migrations/0019_alter_quizsession_served_questions.py
  api/migrations/0019_quizsession_question_colors.py
  api/migrations/0020_quizsession_current_question.py
  api/migrations/0021_merge_20240307_2036.py
  api/migrations/0022_merge_20240522_2132.py
  api/migrations/0023_alter_quizsession_current_question_and_more.py
  api/migrations/0024_settings_quiz_settings.py
  api/migrations/0025_quizsessionstudent_score_and_more.py
  api/migrations/0026_quizsessionstudent_student.py
  api/migrations/0027_remove_quizsessionstudent_student.py
  api/migrations/0028_settings_skip_question_percentage.py
  api/migrations/0029_alter_settings_skip_question_percentage.py
  api/migrations/0030_audiofile.py
  api/migrations/0031_rename_audiofile_instructorrecordings_and_more.py
  api/migrations/0032_alter_instructorrecordings_id.py
  api/migrations/0033_delete_instructorrecordings.py
  api/migrations/0034_instructorrecordings.py
  api/migrations/0035_alter_instructorrecordings_file_and_more.py
  api/migrations/0036_remove_instructorrecordings_file_and_more.py
  api/models.py
  api/routing.py
  api/tests/tests.py
  api/views.py
  api/views/question_views.py
  api/views/quiz_views.py
  api/views/session_views.py
  api/views/user_views.py
  hice_backend/asgi.py
  hice_backend/settings.py
  hice_backend/urls.py
  hice_backend/wsgi.py
  manage.py
  requirements.txt
Labels: 0.1.12

#13 Add HTTPS Support and Configuration for Elastic Beanstalk Environment
  .ebextensions/https-single-instance.config
  .elasticbeanstalk/config.yml
  .platform/nginx/conf.d/https.conf
  .platform/nginx/nginx.conf
  ebsconfig.json
Labels: pr-description, 0.1.13

#15 Refactor: Clean Up Imports and Format Code
  api/views/question_views.py
  api/views/quiz_views.py
  api/views/session_views.py
  api/views/user_views.py
Labels: pr-description, 0.1.15

#14 Enhancements and Bug Fixes in WebSocket Consumers
  api/consumers.py
  api/routing.py
  hice_backend/settings.py
Labels: pr-description, 0.1.14, 0.1.14.1

#16 Create API to Delete Recordings (Restricted by User Ownership)
  api/views/user_views.py
  hice_backend/urls.py
Labels: 0.1.16

#18 Update Nginx Configuration and Add Transcript Functionality
  .platform/nginx/nginx.conf
  api/serializers.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.18, 0.1.18.1, 0.1.18.2, 0.1.18.3

#19 Enhance API Consumers to Handle Quiz Creation Completion Messages
  api/consumers.py
Labels: pr-description, 0.1.19, 0.1.19.1

#20 Feat/delete quiz session
  api/views/session_views.py
  hice_backend/urls.py
Labels: 0.1.20, 0.1.20.1

#21 Sessions by quiz id
  api/views/session_views.py
  hice_backend/urls.py
Labels: 0.1.21

#22 Feat/add title to instructor table
  api/migrations/0038_instructorrecordings_title.py
  api/models.py
Labels: 0.1.22

#23 Bug/login http code
  api/tests/tests.py
  api/views/user_views.py
Labels: 0.1.23, 0.1.23.1

#24 Implement Google Login Endpoint
  api/serializers.py
  api/views/user_views.py
  hice_backend/settings.py
  hice_backend/urls.py
  requirements.txt
Labels: pr-description, 0.1.24, 0.1.24.1
