Repository uncc-hice/edukona_backend, pull requests merged in 2024-08, with the labels that each got.

#1 Refactor Django settings file
  hice_backend/settings.py
Labels: 0.1.1

#5 added the random skip question feature
  api/consumers.py
  api/migrations/0028_settings_skip_question_percentage.py
  api/migrations/0029_alter_settings_skip_question_percentage.py
  api/models.py
  api/views.py
Labels: 0.1.5, 0.1.5.1, 0.1.5.2

#6 Add Instructor Recordings and Audio Upload Functionality with S3 Integration
  api/migrations/0030_audiofile.py
  api/migrations/0031_rename_audiofile_instructorrecordings_and_more.py
  api/migrations/0032_alter_instructorrecordings_id.py
  api/migrations/0033_delete_instructorrecordings.py
  api/migrations/0034_instructorrecordings.py
  api/migrations/0035_alter_instructorrecordings_file_and_more.py
  api/migrations/0036_remove_instructorrecordings_file_and_more.py
  api/models.py
  api/serializers.py
  api/views.py
  hice_backend/settings.py
  hice_backend/urls.py
  requirements.txt
Labels: 0.1.6
