Repository uncc-hice/edukona_backend, pull requests merged in 2024-12, with the labels that each got.

#103 feat: Add Quiz Session Log Functionality
  api/serializers.py
  api/tests/tests.py
  api/views/session_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.103

#101 KAN-224: Add Summaries and Quizzes Chronologically API Endpoint
  api/serializers.py
  api/tests/tests.py
  api/views/recordings_views.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.101, 0.1.101.1, 0.1.101.2

#104 Remove Settings and All References to it
  api/consumers.py
  api/migrations/0061_remove_quiz_settings_delete_settings.py
  api/models.py
  api/serializers.py
  api/tests/consumer_tests.py
  api/views/quiz_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.104

#106 Add JWT Authentication Support
  .github/workflows/websocket-tests.yml
  hice_backend/settings.py
  hice_backend/urls.py
  requirements.txt
Labels: pr-description, 0.1.106

#107 # Add Course Model and Migrations
  api/migrations/0062_course.py
  api/migrations/0063_alter_course_code_alter_course_title.py
  api/migrations/0064_alter_course_code.py
  api/models.py
  api/serializers.py
  api/tests/test_course.py
Labels: pr-description

#108 🔒 Enhanced JWT Token Management with Blacklisting Support
  hice_backend/settings.py
  hice_backend/urls.py
Labels: pr-description, 0.1.108

#111 Implement Google OAuth2 Login Feature
  api/serializers.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.111

#112 KAN-250: Refactor Student Model: Migration and Redefinition
  api/migrations/0065_delete_student.py
  api/migrations/0066_student.py
  api/models.py
Labels: pr-description, 0.1.112

#113 KAN-231: Add CourseStudent model for linking students to courses
  api/migrations/0067_coursestudent.py
  api/models.py
Labels: pr-description, 0.1.113
