Repository uncc-hice/edukona_backend, pull requests merged in 2024-10, with the labels that each got.

#25 Enhance Quiz Retrieval Order in API
  api/views/quiz_views.py
Labels: pr-description, 0.1.25

#26 Fix: Update QuizSession Code Generation Logic
  api/models.py
Labels: pr-description, 0.1.26, 0.1.26.1

#27 Add instructor recording feature to Quiz model
  api/migrations/0039_quiz_instructor_recording.py
  api/models.py
  api/serializers.py
  api/tests/tests.py
  api/views/quiz_views.py
Labels: pr-description, 0.1.27

#29 Migration to Change QuizSession Current Question Relation
  api/migrations/0040_alter_quizsession_current_question.py
  api/models.py
Labels: pr-description, 0.1.29

#30 Enhance API Models with Session and Question Count
  api/models.py
Labels: pr-description, 0.1.30, 0.1.30.1

#31 Enhance QuestionMultipleChoiceSerializer and API Endpoints
  api/serializers.py
  api/tests/tests.py
  api/views/question_views.py
Labels: pr-description, 0.1.31, 0.1.31.1, 0.1.31.2

#32 Add Duration Field to QuestionMultipleChoice Model
  api/migrations/0041_questionmultiplechoice_duration_and_more.py
  api/models.py
  api/serializers.py
  api/tests/tests.py
  api/views/question_views.py
Labels: pr-description, 0.1.32

#33 Handle changed answer
  api/consumers.py
Labels: 0.1.33, 0.1.33.1

#35 Implement a Quiz Session Question Model and Migration Enhancements
  api/migrations/0042_quizsessionquestion_quizsession_served_questions_new.py
  api/migrations/0043_alter_quizsessionquestion_table.py
  api/migrations/0044_auto_20241007_2308.py
  api/migrations/0045_remove_quizsession_served_questions.py
  api/migrations/0046_rename_served_questions_new_quizsession_served_questions.py
  api/migrations/0047_alter_quizsession_served_questions.py
  api/models.py
Labels: pr-description, 0.1.35

#36 Handle response
  api/consumers.py
Labels: 0.1.36

#37 add unlocked field to the QuizSessionQuestion model
  api/migrations/0048_quizsessionquestion_unlocked.py
  api/models.py
Labels: 0.1.37

#38 add fields to QuizSessionQuestion
  api/migrations/0049_quizsessionquestion_extension_and_more.py
  api/models.py
Labels: 0.1.38

#39 Handle locked question
  api/consumers.py
  api/migrations/0050_alter_quizsessionquestion_opened_at.py
  api/models.py
Labels: 0.1.39

#41 add number of participants to quiz sessions response
  api/views/session_views.py
Labels: 0.1.41

#47 Add SendGrid Email Integration for Instructor Welcome Emails
  api/migrations/0006_answer_quizinstance_userprofile_and_more.py
  api/migrations/0007_instructor_questionmultiplechoice_and_more.py
  api/views/user_views.py
  requirements.txt
Labels: pr-description, 0.1.47, 0.1.47.1

#42 Allow instructor to skip question
  api/consumers.py
Labels: 0.1.42, 0.1.42.1, 0.1.42.2

#48 Refactor and Add Profile View Tests
  api/tests/tests.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.48.1

#44 WiP: add and use custom permissions classes
  api/permissions.py
  api/serializers.py
  api/tests/tests.py
  api/views/question_views.py
  api/views/quiz_views.py
  hice_backend/urls.py
Labels: 0.1.44, 0.1.44.1, 0.1.44.2

#52 Update GitHub Actions Workflows for Line Counting and Black Checking
  .github/workflows/line-count.yml
  .github/workflows/python-black-check.yml
Labels: pr-description

#46 Enhance Quiz Functionality and Code Cleanup
  api/consumers.py
  api/models.py
  api/tests/consumer_tests.py
  api/views/session_views.py
  hice_backend/settings.py
  pytest.ini
  requirements.txt
Labels: pr-description, 0.1.46, 0.1.46.1

#50 # Add Contact Message Functionality to API
  api/migrations/0051_contactmessage.py
  api/models.py
  api/serializers.py
  api/tests/tests.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.50

#55 Enhance Quiz Management with Owner Permission and Update Line Count Threshold
  .github/workflows/line-count.yml
  api/permissions.py
  api/tests/test_question_views.py
  api/views/question_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.55, 0.1.55.1

#56 Add Recording and Temporary Credentials Functionality
  api/serializers.py
  api/views/recordings_views.py
  hice_backend/settings.py
  hice_backend/urls.py
Labels: pr-description, 0.1.56, 0.1.56.1

#58 User Deletion Endpoint
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.58

#51 # Implement Sign-Up Feature for Instructors
  api/serializers.py
  api/tests/tests.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.51, 0.1.51.1

#59 Change locking mechanism
  api/consumers.py
Labels: 0.1.59
