Repository uncc-hice/edukona_backend, pull requests merged in 2025-02, with the labels that each got.

#130 Remove redundant comment in QuestionView get method
  api/views/question_views.py
Labels: 0.1.130

#128 KAN-284: Remove Skip Question Feature from Quiz Functionality
  api/consumers.py
  api/management/commands/copysettings.py
  api/migrations/0072_remove_quiz_skip_count_per_student_and_more.py
  api/models.py
  api/serializers.py
  api/tests/consumer_tests.py
  api/tests/test_course.py
Labels: pr-description, 0.1.128

#132 Enhance Quiz Functionality with Skip Question Feature
  api/consumers.py
  api/migrations/0073_quizsessionquestion_skipped_and_more.py
  api/models.py
Labels: pr-description, 0.1.132

#131 # Implement Quiz Scoring API
  api/consumers.py
  api/serializers.py
  api/services.py
  api/tests/test_services.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.131, 0.1.131.1, 0.1.131.2
