Repository uncc-hice/edukona_backend, pull requests merged in 2025-05, with the labels that each got.

#146 [KAN-338] Add Student Reconnect Feature to Quiz API
  api/consumers.py
  api/tests/consumer_tests.py
  api/tests/test_services.py
Labels: pr-description, 0.1.146, 0.1.146.1, 0.1.146.2, 0.1.146.3, 0.1.146.4

#145 [KAN-265] Student Course Join Functionality
  api/permissions.py
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.0.145

#143 [KAN-334] Add Get Course By ID functionality with unit tests
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.143
