Repository uncc-hice/edukona_backend, pull requests merged in 2025-03, with the labels that each got.

#129 Enhance Quiz Functionality with Grade Fetching and Improved Message Handling
  api/consumers.py
  api/services.py
  api/tests/test_services.py
Labels: pr-description, 0.1.129, 0.1.129.1, 0.1.129.2, 0.1.129.3, 0.1.129.4, 0.1.129.5, 0.1.129.6, 0.1.129.7, 0.1.129.8, 0.1.129.9

#135 KAN-291: Enhance Recording Management: Update Functionality and Serializer Improvements
  api/serializers.py
  api/views/recordings_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.135

#139 [KAN-317] Enhance Course Recordings Response with Transcript Status
  api/views/course_views.py
Labels: pr-description, 0.1.139, 0.1.139.1

#138 [KAN-303] Implement Google SSO Authentication
  api/constants.py
  api/serializers.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.138, 0.1.138.1, 0.1.138.2, 0.1.138.3, 0.1.138.4

#142 [KAN-309] Refactor User Response Management and Score Calculation
  api/consumers.py
  api/services.py
  api/tests/test_services.py
Labels: pr-description, 0.1.142, 0.1.142.1

#140 KAN-314: Add Download Recording Functionality
  api/views/recordings_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.140
