Repository uncc-hice/edukona_backend, pull requests merged in 2025-01, with the labels that each got.

#110 KAN-232 Add Course Field and Published Status to Instructor Recordings, Lecture Summaries, and Quizzes
  api/migrations/0068_instructorrecordings_course_and_more.py
  api/models.py
  api/tests/test_course.py
Labels: pr-description, 0.1.110

#114 KAN-233: Course Recordings Management
  api/permissions.py
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.114

#116 Implement JWT Sign-Up Endpoint for Instructors
  api/tests/tests.py
  api/views/user_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.116, 0.1.116.1, 0.1.116.2

#117 KAN-237: Add Course Model Migration and Enhance Course Views
  api/migrations/0069_alter_course_allow_joining_until_and_more.py
  api/models.py
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.117

#115 KAN-234: Add Course-Based Quiz Retrieval Feature
  api/permissions.py
  api/serializers.py
  api/tests/test_course.py
  api/views/quiz_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.115

#118 KAN-236: Add Course Summaries API Endpoint and Tests
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.118

#119 KAN-235: Add Course Student Management API Features
  api/migrations/0070_alter_coursestudent_joined_at.py
  api/models.py
  api/serializers.py
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.119

#121 KAN-268: Enhance Quiz WebSocket Consumer with Quiz Details and User Count
  api/consumers.py
  api/serializers.py
  api/tests/consumer_tests.py
Labels: pr-description, 0.1.121, 0.1.121.1, 0.1.121.2

#122 KAN-238: Implement Course Retrieval for Students
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.122

#123 # Enhance JWT Authentication in WebSocket Consumers
  api/consumers.py
  api/tests/consumer_tests.py
Labels: pr-description, 0.1.123, 0.1.123.1, 0.1.123.2

#125 Enhance Token Handling in Recordings View
  api/views/recordings_views.py
Labels: pr-description, 0.1.125, 0.1.125.1, 0.1.125.2

#124 KAN-267: Enhance Course Summaries Retrieval for Students
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.124

#126 KAN-279: Add Course Creation Functionality
  api/migrations/0071_alter_course_allow_joining_until.py
  api/models.py
  api/serializers.py
  api/tests/test_course.py
  api/views/course_views.py
  hice_backend/urls.py
Labels: pr-description, 0.1.126, 0.1.126.1

#127 # Implement JWT Authentication and Handle Responses
  api/serializers.py
  api/views/user_views.py
Labels: pr-description, 0.1.127
